export const GET_QUIZ_LIST = 'GET_QUIZ_LIST';
export const ADD_ITEM_QUIZ_LIST = 'ADD_ITEM_QUIZ_LIST';
export const DELETE_ITEM_QUIZ_LIST = 'DELETE_ITEM_QUIZ_LIST';
export const UPDATE_ITEM_QUIZ_LIST = 'UPDATE_ITEM_QUIZ_LIST';
